// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dncmrixxantqtyvqawrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuY21yaXh4YW50cXR5dnFhd3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjUyOTUsImV4cCI6MjA2MjkwMTI5NX0.aTo8n0WIiXd-p40lFCcONaMxXwmj7BZcsWmeNcBFBPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);